# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Z5 < Formula
  desc ""
  homepage ""
  version "0.0.5"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/sZma5a/z5/releases/download/v0.0.5/z5_Darwin_x86_64.tar.gz"
      sha256 "48c105f6ffba9d91a554d9ff0fcdedd3dd74250f7b5bef7bcec09b843e114049"

      def install
        bin.install "z5"
        bash_completion.install "completions/goreleaser.bash" => "goreleaser"
        zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
        fish_completion.install "completions/goreleaser.fish"
        man1.install "manpages/goreleaser.1.gz"
      end
    end
    on_arm do
      url "https://github.com/sZma5a/z5/releases/download/v0.0.5/z5_Darwin_arm64.tar.gz"
      sha256 "4129740b5e5734bb6150d2363a3c1a83508987ffda0924669378c8df86d520b6"

      def install
        bin.install "z5"
        bash_completion.install "completions/goreleaser.bash" => "goreleaser"
        zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
        fish_completion.install "completions/goreleaser.fish"
        man1.install "manpages/goreleaser.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sZma5a/z5/releases/download/v0.0.5/z5_Linux_x86_64.tar.gz"
        sha256 "1a6b7271e758f34517fe28fb792e56d4001ad906f598aa1d3e02177bb3ebac66"

        def install
          bin.install "z5"
          bash_completion.install "completions/goreleaser.bash" => "goreleaser"
          zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
          fish_completion.install "completions/goreleaser.fish"
          man1.install "manpages/goreleaser.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sZma5a/z5/releases/download/v0.0.5/z5_Linux_arm64.tar.gz"
        sha256 "ac79e7e15c2183602942a9a32ad106cfe2ca6127e9b9e057e089b1c18cc1ce14"

        def install
          bin.install "z5"
          bash_completion.install "completions/goreleaser.bash" => "goreleaser"
          zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
          fish_completion.install "completions/goreleaser.fish"
          man1.install "manpages/goreleaser.1.gz"
        end
      end
    end
  end

  conflicts_with "goreleaser-pro"
end
